# Generated by Django 3.2.12 on 2022-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=267, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=267, null=True),
        ),
    ]
